title: Not Your Mother's Mormonism
description: Not Your Mother's Mormonism — A Personal Blog For Mormons, ExMormons And Everyone In Between

url: https://mormonism.jaredrummler.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: jaredrummler
  twitter: jaredrummler
  email: jaredrummler@gmail.com

google_analytics: "UA-103167181-1"
